#!/usr/bin/env bash
# -t rsa: Specifies that the key type should be RSA.
# -b 4096: Specifies that the key should be 4096 bits in length.
# -f ~/.ssh/school: Specifies the filename and location of the private key file.
# -N 'betty': Specifies the passphrase to be used to protect the private key.

ssh-keygen -t rsa -b 4096 -f school -N betty
